export const DEFAULT_PRODUCT_CATEGORIES: {
  name: string;
  normalizedName: string;
}[] = [
  { name: 'Cervejas', normalizedName: 'cervejas' },
  { name: 'Chopes', normalizedName: 'chopes' },
  { name: 'Cervejas sem álcool', normalizedName: 'cervejas sem alcool' },
  { name: 'Refrigerantes', normalizedName: 'refrigerantes' },
  { name: 'Energéticos', normalizedName: 'energeticos' },
  { name: 'Isotônicos', normalizedName: 'isotonicos' },
  { name: 'Água mineral sem gás', normalizedName: 'agua mineral sem gas' },
  { name: 'Água mineral com gás', normalizedName: 'agua mineral com gas' },
  { name: 'Água de coco', normalizedName: 'agua de coco' },
  { name: 'Sucos', normalizedName: 'sucos' },
  { name: 'Chás prontos', normalizedName: 'chas prontos' },
  { name: 'Bebidas lácteas', normalizedName: 'bebidas lacteas' },
  { name: 'Bebidas funcionais', normalizedName: 'bebidas funcionais' },
  { name: 'Bebidas vegetais', normalizedName: 'bebidas vegetais' },
  { name: 'Kombuchas', normalizedName: 'kombuchas' },
  { name: 'Cidras', normalizedName: 'cidras' },
  { name: 'Vinhos tintos', normalizedName: 'vinhos tintos' },
  { name: 'Vinhos brancos', normalizedName: 'vinhos brancos' },
  { name: 'Vinhos rosés', normalizedName: 'vinhos roses' },
  { name: 'Espumantes', normalizedName: 'espumantes' },
  { name: 'Champagnes', normalizedName: 'champagnes' },
  { name: 'Proseccos', normalizedName: 'proseccos' },
  { name: 'Destilados', normalizedName: 'destilados' },
  { name: 'Whisky', normalizedName: 'whisky' },
  { name: 'Vodka', normalizedName: 'vodka' },
  { name: 'Gin', normalizedName: 'gin' },
  { name: 'Rum', normalizedName: 'rum' },
  { name: 'Tequila', normalizedName: 'tequila' },
  { name: 'Cachaça', normalizedName: 'cachaca' },
  { name: 'Licores', normalizedName: 'licores' },
  { name: 'Aperitivos e vermutes', normalizedName: 'aperitivos e vermutes' },
  { name: 'Coquetéis prontos', normalizedName: 'coqueteis prontos' },
  { name: 'Bebidas sem álcool', normalizedName: 'bebidas sem alcool' },
  { name: 'Xaropes e mixers', normalizedName: 'xaropes e mixers' },
  { name: 'Tônicas', normalizedName: 'tonicas' },
  { name: 'Gelo', normalizedName: 'gelo' },
  { name: 'Carvão', normalizedName: 'carvao' },
  { name: 'Copos e descartáveis', normalizedName: 'copos e descartaveis' },
  { name: 'Snacks e petiscos', normalizedName: 'snacks e petiscos' },
  { name: 'Kits e combos', normalizedName: 'kits e combos' },
  { name: 'Outros', normalizedName: 'outros' },
];
